### ISSUE TITLE
Failed upload causes studio to crash

### ISSUE THREAD

**Issue by homerjam** [sanity-io/sanity-plugin-mux-input#102]
<img width="786" alt="Screenshot 2022-10-03 at 15 45 53" src="https://user-images.githubusercontent.com/1055769/193606616-068f4a0b-3fa8-45fe-a82c-30bb4fcf61a7.png">

**Comment by hdoro** [comment]
@homerjam can you confirm this is still an issue?

**Comment by homerjam** [comment]
Ha definitely can't I'm afraid, mux and sanity now multiple versions forward so may as well close
