### ISSUE TITLE
Disable removing asset from Mux

### ISSUE THREAD

**Issue by matt-sanders** [sanity-io/sanity-plugin-mux-input#126]
When an asset is referenced between two documents, a user can still choose to delete the asset from Mux when removing the video from a document. If you try and do this a mutation error will display. Would it be possible to either:
1. Have the option to disable removing from Mux completely ( we'd prefer to manage these within Mux )
2. Stop users from removing from Mux if the asset is referenced elsewhere ( similar to how Sanity alerts when a document has references ), either by prompting the user or just disabling the option at all ( e.g. display a "This asset is used by other documents. You cannot delete it from Mux" notice )

Thanks!

**Comment by hdoro** [comment]
@matt-sanders as of `^2.2.0`, you can now check/uncheck the option to also delete the asset on Mux. If negative, we won't remove it from your Mux environment.

The deletion workflow is also aware of references to the video - if any document uses it, you won't be able to delete it.

**Comment by matt-sanders** [comment]
Thank you!
