### ISSUE TITLE
Audio preview/browse gives errors

### ISSUE THREAD

**Issue by biowatch-andersnielsen** [sanity-io/sanity-plugin-mux-input#128]
Uploading audio files works, but browsing assets with audio files gives an error due to no thumbnails being found in the UI as well as in the console.

<img width="405" alt="CleanShot 2022-10-24 at 09 09 38@2x" src="https://user-images.githubusercontent.com/110821377/197467856-b367d90c-4022-42a2-b1df-2bbf9fdb6cd5.png">

<img width="204" alt="CleanShot 2022-10-21 at 10 24 03@2x" src="https://user-images.githubusercontent.com/110821377/197467264-df68fcf6-0f63-4d94-a5a1-7ae0ec7eb847.png">

I understand that the plugin is for video, but Mux supports audio and the errors seems to come only because of the thumbnail preview.

A possible solution to support this is by changing the preview in browse (for example to a list of file names, only attempting to show thumbnails when they are present)

I'm using Mux plugin 1.1.9 on Sanity 2.35.0

**Comment by hdoro** [comment]
Fixed as of the upcoming `2.4.0` release. The Mux player is now adapted to playing audio

![Updated audio player](https://github.com/sanity-io/sanity-plugin-mux-input/assets/27744332/efb24bb5-cbe5-4710-9c9d-f48e897940d7)

![Example videos dashboard with an audio file](https://github.com/sanity-io/sanity-plugin-mux-input/assets/27744332/07ded18d-5b67-4cde-b3e9-4db51011a6b7)
