### ISSUE TITLE
CORS error when uploading video

### ISSUE THREAD

**Issue by wrux** [sanity-io/sanity-plugin-mux-input#129]
I'm trying to setup the plugin in Studio v2, but it looks like I'm getting CORS issues. I've followed the setup guide and added the API credentials, but it looks like there's an issue with the request. 

Any idea on how to resolve this?

Here's the deps in my Studio instance:

```json
"dependencies": {
  "@sanity/base": "^2.25.1",
  "@sanity/cli": "^2.30.0",
  "@sanity/components": "^2.14.0",
  "@sanity/core": "^2.25.0",
  "@sanity/dashboard": "^2.26.0",
  "@sanity/default-layout": "^2.25.1",
  "@sanity/default-login": "^2.24.1",
  "@sanity/desk-tool": "^2.25.3",
  "@sanity/production-preview": "^2.29.3",
  "@sanity/vision": "^2.25.4",
  "bcp47": "^1.1.2",
  "get-youtube-id": "^1.0.1",
  "prop-types": "^15.7",
  "react": "^17.0",
  "react-dom": "^17.0",
  "react-icons": "^4.3.1",
  "react-youtube": "^8.2.1",
  "sanity-plugin-dashboard-widget-document-list": "^0.0.13",
  "sanity-plugin-iframe-pane": "^1.0.16",
  "sanity-plugin-media": "^1.4.4",
  "sanity-plugin-mux-input": "^1.1.9",
  "sanity-plugin-vercel-deploy": "^2.1.6",
  "styled-components": "^5.3.3"
}
```

A few screenshots:

<img width="380" alt="Screenshot 2022-10-26 at 22 34 47" src="https://user-images.githubusercontent.com/1453384/198055917-26c6a5bb-4c63-430d-89ae-07b7e5c91de9.png">

<img width="1419" alt="Screenshot 2022-10-26 at 22 35 44" src="https://user-images.githubusercontent.com/1453384/198055943-0b4c0d00-3c91-4cb4-951b-4e4d97642a22.png">

**Comment by wrux** [comment]
> having the same cors issue on sanity v3

Me too

**Comment by bjoerge** [comment]
Do you happen to have wildcard URLs in your project's list of allowed CORS origins? If so - we have identified the problem and will make sure it get fixed.

In the meantime you can try working around this issue by adding your Studio URL without wildcards to CORS origins here: `https://www.sanity.io/organizations/<your org>/project/<your project>/api#cors-origins`

**Comment by hdoro** [comment]
@bjoerge I'm assuming this has been fixed in the Mux addon backend? Can we close this issue?
