### ISSUE TITLE
Allow configuring playback_policy

### ISSUE THREAD

**Issue by israelroldan** [sanity-io/sanity-plugin-mux-input#16]
Hi guys!

First of all, awesome work with the plugin!

This is an awesome plugin and offers the exact functionality the majority of mux users need, however... it seems there's no way to configure `playback_policy` for direct uploads? This must be specified when creating the Video upload URL which IIUC is currently done server side in sanity side (`/addons/mux/uploads/${studioClient.clientConfig.dataset}` endpoint).

Just like the `MUX-Proxy-UUID` is currently passed as `passthrough`, there should be a way to specify something like `MUX-Proxy-Playback-Policy` in case we want to specify a `'signed'` policy (and not the default 'public' one).

It seems that for the case of pasting a video URL into the field, this is already possible, but that's because it is a different endpoint than direct uploads.

For the time being I have implemented this on my own outside of sanity but I'd love to be able to offer this form input in the studio.

**Comment by paalwilliams** [comment]
Yeah, this would be a great addition!

**Comment by dylanjha** [comment]
@israelroldan @paalwilliams this was completed in #22 

🙌 please try it out and let us know how it works for you!
