### ISSUE TITLE
Uploading video file crashes desk.. even on demo.

### ISSUE THREAD

**Issue by paalwilliams** [sanity-io/sanity-plugin-mux-input#17]
Hi,

A bit flustered by this one. No matter what I do, I cannot get Sanity Desk to play nicely with this plugin.

I'll add a schema according to the spec, copying and pasting whats below:

```
    {
      title: "Video blog post",
      name: "videoBlogPost",
      type: "document",
      fields: [
        { title: "Title", name: "title", type: "string" },
        {
          title: "Video file",
          name: "video",
          type: "mux.video"
        }
      ]
    }
```

And no matter the file size or duration, each time it crashes Sanity Desk with this error: 

```
Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at checkForNestedUpdates (/static/js/vendor.bundle.js:28133:15)
    at scheduleUpdateOnFiber (/static/js/vendor.bundle.js:26204:3)
    at Object.enqueueSetState (/static/js/vendor.bundle.js:17670:5)
    at MuxVideo.956.Component.setState (/static/js/vendor.bundle.js:3554:16)
    at MuxVideo.componentDidUpdate (/static/js/app.bundle.js:97380:14)
    at MuxVideo.componentDidUpdate (/static/js/app.bundle.js:245636:123)
    at commitLifeCycles (/static/js/vendor.bundle.js:24877:22)
    at commitLayoutEffects (/static/js/vendor.bundle.js:27843:7)
    at HTMLUnknownElement.callCallback (/static/js/vendor.bundle.js:5197:14)
```

My Schema within the default schema file is configured as such: 

```
// First, we must import the schema creator
import createSchema from 'part:@sanity/base/schema-creator'

// Then import schema types from any plugins that might expose them
import schemaTypes from 'all:part:@sanity/base/schema-type'

// Then we give our schema to the builder and provide the result to Sanity
export default createSchema({
  // We name our schema
  name: 'movie',
  // Then proceed to concatenate our document type
  // to the ones provided by any plugins that are installed
  types: schemaTypes.concat([
    {
        title: "Example Document Type",
        name: "exampleDocumentType",
        type: "document",
        fields: [
            {
                title: "Greeting",
                name: "greeting",
                type: "string"
            },
            {
                title: "Video file",
                name: "video",
                type: "mux.video"
            }
        ]
    }
  ])
})
```

The video, however, does seem to successfully upload to Mux. So I'm a bit unclear why this crash is happening.
For the record, I've tried this with both the Movies demo thats available as well as starting my own project. This product was basically exactly what I was looking for so this is quite frustrating.

**Comment by p10e** [comment]
Hi Paal,

How frustrating indeed. Let's try to resolve this one. To help us reproduce the issue, could you share what versions of Sanity you are on? You can find out by running `sanity versions` in the CLI (or checking your `package.json` file).

Also, are you in our [Slack community](https://slack.sanity.io/) by any chance? If so, please feel free to reach out to `@Peter` in DM so we can troubleshoot in real-time.

**Comment by paalwilliams** [comment]
Hi there!

Sanit versions outputs 

```
@sanity/cli  1.150.7 (up to date)
```

I'm not in the slack community - but I'll definitely join.

**Comment by rosnovsky** [comment]
Hey folks, 
I have the same issue. Sanity CLI 2.0.1. Was this resolved?

**Comment by paalwilliams** [comment]
Hey @rosnovsky ,

I unfortunately went another direction with the CMS as I couldn't figure out what was causing this.

Things that fixed it for me, (although I'm not sure this is a permanent fix but seemed to fix some things).

- Disabling all cookie and content tracking my browser. (This fixed me being unable to login with Firefox).
- Using a different OS. I still have not gotten MacOS to work with Sanity and Mux.

Things I tried that didn't fix it for me, but might still be worth a shot:

- Reinstalling NodeJS.
- Manually updating to latest version of NodeJS.
- Reinstalling Sanity CLI
- Installing Node, NPM through a package manager (homebrew)
- Installing Node, NPM through regular downloadable installer
- Installing Node, NPM through cURL

Here is my final comment from the slack conversation w/ Sanity.

> This plugin does indeed work on a different computer with Pop! OS through Firefox.

> On MacOS, I've tried changing my Node version to match what was on my Pop! OS machine, that did not work. I've tried Chromium, Firefox Nightly, Safari, and Chrome.

> I had not gotten the chance to properly test Firefox, as I could not get the login to work. I had to disable all of my tracking protections in Firefox to get the login to work (probably due to the login cookie). Once I did that, I can properly view an uploaded video.

> Chromium is where I was having the issues when I made this post. All of the output was from Chromium, if that makes any difference. Still having issues with the sanity studio crashing in Chromium.

> Safari is basically unresponsive until I disabled all of the cross site tracking. It currently is still unable to load the Sanity Dashboard, however (stuck at connecting to sanity.io....)

> Chrome seems to be functioning perfectly, however, there is still error output in the console. Firefox is also functioning well, but still has similar error output.

```

Unfortunately it seems like there's some kind of bug with Sanity CLI for Mac and this plugin that only affects certain browsers. As far as I'm aware there hasn't been a fix implemented.

**Comment by rosnovsky** [comment]
Yeah... I tried a bunch of things, including trying Linux, different browsers, and I'm not sure the issue is there.

There must be some sort of a loop that constantly sets input field state as soon as the video is uploaded. I'd love to take a shot at fixing it, but I'm unsure where to look and what to look for :/

**Comment by paalwilliams** [comment]
yeah, sorry man. I'm still not totally sure why switching OS would even resolve it, considering its a very similar environment, same node version, etc. 

And yeah - I'm in agreement with you it seems to be related to the state on upload. In any case this plugin definitely isn't able to be shipped to clients at this point, so here's hoping they patch it soon.

**Comment by dylanjha** [comment]
@rosnovsky @paalwilliams I tried and I was unable to repro this. I would <3 to get a repro case (Mac) so that I can work on a patch. I'm running sanity locally

**Comment by rosnovsky** [comment]
I don't know what I did ~wrong~ right, but reinstalling the plugin solved it for me. No clue why or how 🤷
