### ISSUE TITLE
Adding Credentials API call is returning a 502 error

### ISSUE THREAD

**Issue by krilo** [sanity-io/sanity-plugin-mux-input#18]
```
curl 'https://3sysi6ek.api.sanity.io/v1/addons/mux/secrets/production/test' \
  -H 'authority: 3sysi6ek.api.sanity.io' \
  -H 'accept: application/json' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.193 Safari/537.36' \
  -H 'origin: http://localhost:3333' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: http://localhost:3333/' \
  -H 'accept-language: en-GB,en-US;q=0.9,en;q=0.8,nl;q=0.7,fr;q=0.6,no;q=0.5,es;q=0.4,da;q=0.3,de;q=0.2,sv;q=0.1,ja;q=0.1' \
  -H 'cookie: sanitySession=REDACTED' \
  --compressed
```

Returns ```{"statusCode":502,"error":"Bad Gateway","message":"api.mux.com responded with 404 (The requested resource either doesn't exist or you don't have access to it.)"}```

Not sure if this is the best place to file the issue since it seems to be a issue with the Sanity API more than the plugin. Let me know if there is a better place I can post this issue. Thanks :)

**Comment by dylanjha** [comment]
@krilo thanks for reporting! I'll have a look and see if we can track this down. Is it easily reproducible/happens every time you try to add credentials?

**Comment by krilo** [comment]
@dylanjha Thanks for the quick reply :D Yes this happens consistently, steps to reproduce are as follows

1. Install the sanity plugin
2. Add mux.video type to schema (See my schema below)
3. Navigate to a entity that uses the mux
4. Be asked by plugin to add my credentials and do so by clicking the config icon and add the access key, secret and pressing submit.

Earlier today was the first time I tried using the plugin and I have not been able to submit the keys and secret successfully. 

`{
          title: 'Images & Videos',
          name: 'items',
          type: 'array',
          of: [{type: 'image'}, {title: "Video", type: 'mux.video'}]
        }`

**Comment by dylanjha** [comment]
@krilo can you make sure your access token has "Full Access" to Mux Video and also "Read" access to Mux Data please? Currently, the integration needs Mux Data read access in order to get through the step of verifying credentials.

 
<img width="828" alt="Screen Shot 2020-11-10 at 6 27 13 AM" src="https://user-images.githubusercontent.com/764988/98687544-b5bd3880-231e-11eb-9be3-45bbbad8145b.png">

**Comment by krilo** [comment]
Oh no, I had not added Read for Mux Data and not the install steps works exactly as expected. I was following this guide https://www.sanity.io/blog/first-class-responsive-video-support-with-the-new-mux-plugin but clearly missed the requirement of having to give access to Mux Data. My bad. 

Thank you so much for the help with this.

**Comment by dylanjha** [comment]
No worries! I'll actually work to get that updated. We really _shouldn't_ need data Read access for this integration. Thanks for posting, I'm sure other people have run into this!
