### ISSUE TITLE
Ability to upload a mux video via Sanity programatically 

### ISSUE THREAD

**Issue by pastinepolenta** [sanity-io/sanity-plugin-mux-input#180]
**Is your feature request related to a problem? Please describe.**
Ability to upload a Mux video using the @sanity/client like we can do for images and files

**Describe the solution you'd like**
The mux video is uploadable via JS script instead of using the dashboard

**Describe alternatives you've considered**
Looking at the source code of the mux plugin and repeating the same code that plugin is doing internally, or just give up and load the videos manually in the dashboard

**Comment by hdoro** [comment]
This is not in scope for this plugin [as explained here](https://github.com/sanity-io/sanity-plugin-mux-input/issues/32#issuecomment-1954759236). Thank you for the valuable suggestion and for the patience, Mirko!
