### ISSUE TITLE
Sanity Asset Missing Mux Asset Information

### ISSUE THREAD

**Issue by dgrbrady** [sanity-io/sanity-plugin-mux-input#19]
Hello all, I'm having some problems using the `mux-input` plugin. When I open the sanity studio, I can choose a video and upload it successfully to Mux, but when I try to use GROQ to retrieve information about the video, the information is incomplete. I have followed the set up guides exactly, but I am new to Sanity and Mux so I may be missing something. Anyway, here is is my `course.js` schema:

```javascript
export default {
  title: "Video course",
  name: "videoCourse",
  type: "document",
  fields: [
    { title: "Title", name: "title", type: "string" },
    { title: "Video file", name: "video", type: "mux.video" },
  ]
}
```

and I've made sure to import it in my `schema.js`:

```javascript
// import createSchema and schemaTypes
import course from "./course";
export default createSchema({
  name: "default",
  types: schemaTypes.concat([
    category,
    // others
  ])
})
```

What my Sanity studio looks like:

![sanity-studio-flame](https://user-images.githubusercontent.com/38011308/98834312-0c08a500-240d-11eb-995f-e40f5be865f0.png)

Proof the video was uploaded to Mux:

![mux-flame](https://user-images.githubusercontent.com/38011308/98834376-22166580-240d-11eb-8511-32881a51d14c.png)

However this is what I get when I use GROQ from Sanity Vision:
![sanity-vision](https://user-images.githubusercontent.com/38011308/98834571-5c800280-240d-11eb-8445-fb9446592538.png)

What am I missing to get the asset information from Mux like the playback ID?

Thanks for any help!

**Comment by dylanjha** [comment]
Hi @dgrbrady see about "Expanding References" here: https://www.sanity.io/docs/how-queries-work#expanding-references-8ca3cefc3a31

You'll want to do something like:

```
*[_type == "videoCourse"] {
  _id, title
  vide.asset->
}
```

This is just how GROQ works, when you have a reference to a different document, you need to tell GROQ to expand it. Try that please!

**Comment by dgrbrady** [comment]
> Hi @dgrbrady see about "Expanding References" here: https://www.sanity.io/docs/how-queries-work#expanding-references-8ca3cefc3a31
> 
> You'll want to do something like:
> 
> ```
> *[_type == "videoCourse"] {
>   _id, title
>   vide.asset->
> }
> ```
> 
> This is just how GROQ works, when you have a reference to a different document, you need to tell GROQ to expand it. Try that please!

Wow it was just that simple (had to do `video->` instead of `video.asset->` but that worked! Thank you so much for the quick response. I probably would have been stuck on this all day lmao
