### ISSUE TITLE
Error when uploading video: Cannot read properties of undefined (reading 'dataset')

### ISSUE THREAD

**Issue by psntr** [sanity-io/sanity-plugin-mux-input#215]
Maybe related to post from #213 but the error log is different. ~~Happens in `v2.0.11` only.~~
***EDIT: happens in `v2.0.10` as well.**

<img width="802" alt="Screenshot 2023-02-22 at 13 55 21" src="https://user-images.githubusercontent.com/20617539/220528253-29c68523-b64b-4d52-8150-f57e1a892e36.png">
<img width="475" alt="Screenshot 2023-02-22 at 14 10 27" src="https://user-images.githubusercontent.com/20617539/220528264-096f4aa4-f616-4979-8174-72b46f255ae9.png">

**Comment by guictrl** [comment]
Similar error I just started getting: 
<img width="639" alt="image" src="https://user-images.githubusercontent.com/47580888/220815826-e6e6dc65-abea-496f-bdf5-67f27cc1b338.png">

**Comment by phmasek** [comment]
Since Sanity migrated to `@sanity/client v5` this started. The migration happened at `v3.4.0` so if you rollback Sanity to `v3.3.1` you should be able to use `sanity-plugin-mux-input` normally.

**Comment by psntr** [comment]
Issue fixed with latest release `v.2.0.15`
