### ISSUE TITLE
Failing to prompt for mux credentials on first use

### ISSUE THREAD

**Issue by cedjud** [sanity-io/sanity-plugin-mux-input#23]
#### Issue description

Using v0.3.0.
While using the plugin for the first time a spinner with a message saying "Fetching credentials" appears. I have not previously added the credentials. Meanwhile the button to toggle the credentials prompt doesn't do anything.

#### Steps to reproduce the issue

1.  Install the plugin in a new project
2. Add schema making use of the "mux-input" as described in the readme
3. Start the Sanity Studio

#### What's the expected result?

- To be able to toggle the credentials dialog and add the Mux Token ID and the Mux token secret.

#### What's the actual result?

- The button doesn't toggle the prompt and a message saying "fetching credentials" appears.

#### Additional details / screenshot

- ![Kapture 2021-02-09 at 11 52 52](https://user-images.githubusercontent.com/5310895/107366336-510ca800-6ade-11eb-98a4-c84e992cb6b4.gif)
- Installing v0.2.1 allowed me to add the credentials.
- After adding the credentials using v0.2.1 I upgraded to v0.3.0 and it worked as expected using the credentials.

**Comment by erikpena** [comment]
Hello @cedjud,
First off, thank you for the thorough repro.  It led me directly to the root of the issue.  I'll be submitting a PR for this here shortly. 😁

**Comment by rexxars** [comment]
Fixed in v0.3.1 - thanks for reporting!
