### ISSUE TITLE
Previews not loading

### ISSUE THREAD

**Issue by benbesen** [sanity-io/sanity-plugin-mux-input#237]
I'm havnig issues with the video thumbnails not loading properly. Very rarely one or two images load, but most of the time they don't load. There is continuos traffic to the mux servers while the images are loading. Video playback within the field works fine so I'm assuming it's not an issue with the signing.

Here are the packages I'm using

`    "@sanity/base": "^2.0.0",
    "@sanity/cli": "^3.2.6",
    "@sanity/default-layout": "^2.0.0",
    "@sanity/default-login": "^2.0.0",
    "@sanity/desk-tool": "^2.0.0",
    "@sanity/eslint-config-studio": "^2.0.0",
    "@sanity/form-builder": "^2.35.5",
    "@sanity/vision": "^3.2.6",
    "eslint": "^8.6.0",
    "htm": "^3.1.1",
    "prop-types": "^15.7",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-icons": "^4.7.1",
    "sanity": "^3.2.6",
    "sanity-plugin-mux-input": "^2.0.16",
    "styled-components": "^5.2.0"`

https://user-images.githubusercontent.com/10700180/225431018-9ed28a04-a10d-4b50-b384-203eb78cacfa.mov

**Comment by benbesen** [comment]
I just researched a bit more, it's loading the previews but not displaying them. But can't figure out why...
The signed streaming and thumbnail loading in the front-end works fine.

https://user-images.githubusercontent.com/10700180/226356173-3c2e83b5-5b40-43c9-80d0-bc8efe91b968.mp4

**Comment by jonabc** [comment]
I believe this was fixed in https://github.com/sanity-io/sanity-plugin-mux-input/pull/253.  If you're still seeing this issue in recent versions please reopen 🙏
