### ISSUE TITLE
Signed videos cause plugin to crash on version 2.0.16

### ISSUE THREAD

**Issue by roblom** [sanity-io/sanity-plugin-mux-input#239]
Upgrading from v 2.0.8 to 2.0.16 causes the plugin to crash.

EDIT: I now found the issue https://github.com/sanity-io/sanity-plugin-mux-input/issues/224 having the same problem for audio files, I guess the answer to #224 will be the same valid here as well..

![image](https://user-images.githubusercontent.com/738522/225906627-5fe6da76-0fc7-4db2-9b49-edad5c95c5b5.png)
```
Uncaught TypeError: Right-hand side of 'instanceof' is not an object
    at yo.exports (sign.js:108:39)
    at generateJwt (generateJwt.ts:35:10)
    at getVideoSrc (getVideoSrc.ts:18:19)
```
generateJwt.ts is from your plugin while sign.js comes from jsonwebtoken-esm
and the latter seems to be the problem.

If I downgrade to v2.0.8 if works, but if I the (git clone jsonwebtoken-wem + build + copy the "dist" folder into the dist of "<my app>/node_modules\jsonwebtoken-esm" (which is present here in my app because this plugin requires it), I get the same error.

Problem seems to be (in jsonwebtoken-esm v2.0.1 that the browser tries to require crypto (from node)
```
const { KeyObject, createSecretKey, createPrivateKey } = require('crypto')
```
while in v 1.0.5 (that comes with sanity-plugin-mux-input v 2.0.8) this seems to have been successfully browserifyd

So not directly your problem, but please look into it, if you can :)
For now I will keep v 2.0.8 as we are using signed videos.

**Comment by torrfura** [comment]
What version of sanity are you running to get this to work? We're setting up a new project and are ending up running in circles to get this plugin to work, no combinations of version so far has worked for us.

**Comment by trulymittal** [comment]
Same here nothing works for **signed urls**: 
`sanity-plugin-mux-input 2.0.16 / 2.0.8 / 2.0.9 / 2.0.12`
`sanity 3.2.0 / 3.7.1`
