### ISSUE TITLE
ESM issue trying to use plugin inside Next.js

### ISSUE THREAD

**Issue by heggemsnes** [sanity-io/sanity-plugin-mux-input#274]
Using Sanity 3.11.1 and Next.js 13.4.3:

```
./node_modules/.pnpm/sanity-plugin-mux-input@2.0.17_@types+react-dom@18_my5uenwqbtcd3ukesooh24rbh4/node_modules/sanity-plugin-mux-input/lib/_chunks/Input-42aef09c.cjs:1:1110
Module not found: ESM packages (media-chrome/dist/react) need to be imported. Use 'import' to reference the package instead. https://nextjs.org/docs/messages/import-esm-externals

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/.pnpm/sanity-plugin-mux-input@2.0.17_@types+react-dom@18_my5uenwqbtcd3ukesooh24rbh4/node_modules/sanity-plugin-mux-input/lib/_chunks/index-3999f947.cjs
./node_modules/.pnpm/sanity-plugin-mux-input@2.0.17_@types+react-dom@18_my5uenwqbtcd3ukesooh24rbh4/node_modules/sanity-plugin-mux-input/lib/index.cjs
./node_modules/.pnpm/sanity-plugin-mux-input@2.0.17_@types+react-dom@18_my5uenwqbtcd3ukesooh24rbh4/node_modules/sanity-plugin-mux-input/lib/index.cjs.js
./sanity/sanity.config.tsx
./src/app/studio/[[...index]]/page.tsx
```

**Comment by marnauortega** [comment]
@Vintotan What sanity studio version do you have installed? Don't you have conflicts when running `npm i sanity-plugin-mux-input@studio-v3`?

**Comment by jonabc** [comment]
Would someone in this issue that encountered the original problem mind trying out the new [release 2.1.0](https://github.com/sanity-io/sanity-plugin-mux-input/releases/tag/v2.1.0) without the `esmExternals: 'loose'` setting and see if that release fixes the underlying issue?  I encountered a similar error while working on https://github.com/sanity-io/sanity-plugin-mux-input/pull/289, though I didn't reproduce the case from this bug report so can't say for certain whether this has been fixed or not.

**Comment by hdoro** [comment]
I was not able to reproduce with plugin version `2.3.4`, Sanity `3.40` and Next `v14.2.3` - can you confirm if this is still an issue, @heggemsnes ?
