### ISSUE TITLE
Can't remove video from document

### ISSUE THREAD

**Issue by nboliver** [sanity-io/sanity-plugin-mux-input#28]
Our schema has videos nested within an array of content modules. Once a video is set, you can't remove it from the document, unless you delete the parent module / object. 

When you remove it using these settings, it appears the video is gone:
![image](https://user-images.githubusercontent.com/3094055/115284227-42a3c380-a101-11eb-8dfe-30ca515cf789.png)

![image](https://user-images.githubusercontent.com/3094055/115284211-3e77a600-a101-11eb-9505-b81b8594c513.png)

However, when you inspect the document (or even re-open the edit modal for the array item) the video is back:

![image](https://user-images.githubusercontent.com/3094055/115284378-7848ac80-a101-11eb-93f2-d22ec3133497.png)

This seems like it could be related to https://github.com/sanity-io/sanity-plugin-mux-input/issues/11

**Comment by gristleism** [comment]
Ran into this today, client couldn't remove an optional video from the CMS so had to manually disable it in the frontend codebase.
