### ISSUE TITLE
Pull / Sync existing Mux Videos

### ISSUE THREAD

**Issue by lukasentebbe** [sanity-io/sanity-plugin-mux-input#290]
Hi,

is there a way to sync existing Videos which has been uploaded to Mux? If there are already Videos on Mux and i connect Sanity they do not show up in the Sanity Media Folde. Same when i switch tokens. I think this is very much needed, but maybe i also got something wrong.

Thanks!
best
lukas

**Comment by sharpsteelsoftware** [comment]
same here. the plugin is broken (see "is not a function" issue). since there is no mux sync or pull existing videos my upload flow is completely blocked dead

**Comment by Crowl3y** [comment]
+1 this is causing me issues too. Any assets not uploaded via sanity or uploaded by a different sanity project (swapped token to a different project) do not show up. At that point its kind of un-useable, or you have to re-upload all the assets again and delete the originals from within mux

**Comment by sharpsteelsoftware** [comment]
I don't think the authors of this library can help us but I agree this is a major problem. In fact I'd even go so far to say that this is a game breaker for the nextjs plus headless cms sanity stack. People can't spend days or weeks studying the intricate complexity of vercels cache upon cache. Especially when it changes every few months. Best thing to do is provide this feedback to nextjs vercel and let them know they can do better to keep us happy

**Comment by khushkaranbajwa** [comment]
Seems similar to #53 where there also hasn't been a resolution.
