### ISSUE TITLE
The mux-input plugin crashed: Invalid credentials

### ISSUE THREAD

**Issue by Vintotan** [sanity-io/sanity-plugin-mux-input#297]
Hi,

I get the error message that the mux-input plugin crashed and that the credentials are invalid. 

<img width="1901" alt="Screenshot 2023-07-19 at 17 19 28" src="https://github.com/sanity-io/sanity-plugin-mux-input/assets/39995527/498ce564-b6d3-4f92-a95b-b21f516c25b7">

<img width="1067" alt="Screenshot 2023-07-19 at 17 19 42" src="https://github.com/sanity-io/sanity-plugin-mux-input/assets/39995527/eed9762f-543f-4a3f-ba9f-6503c228eab3">

I have created a new access token in my Mux dashboard. How can I set my new generated access token? I already tried to remove the sanity-plugin-mux-input and install it again but it doesn't work. Basically, I want to popup this window:

<img width="477" alt="Screenshot 2023-07-19 at 17 32 45" src="https://github.com/sanity-io/sanity-plugin-mux-input/assets/39995527/80474730-549d-4acd-b8d2-5e5cec440d0a">

I use:
- "next-sanity": "^5.1.1"
- "sanity-plugin-mux-input": "^2.1.1"

Cheers

**Comment by byebyers** [comment]
Is there not a way to clear credentials so we can apply new ones?
