### ISSUE TITLE
videos are displayed twice in sanity 

### ISSUE THREAD

**Issue by PhilippLiebhart** [sanity-io/sanity-plugin-mux-input#298]
Dear Community,
i have integrated the mux.video plugin and it works all fine.
the only thing is that the uploaded videos are displayed twice in the browser… did anyone have the same problem? Any clues how to fix this?
i also double checked - the video is only uploaded once…

here a screenshot:
![Screenshot 2023-07-25 at 12 53 15](https://github.com/sanity-io/sanity-plugin-mux-input/assets/62606411/b8e3a6e1-dc6d-4672-b5ae-53be7073aa33)

**Comment by sharpsteelsoftware** [comment]
uploading by url creates two copies in mux for me

**Comment by hdoro** [comment]
@PhilippLiebhart @sharpsteelsoftware  can you confirm that this is still an issue in the latest version? (`2.2.4` or above)

**Comment by PhilippLiebhart** [comment]
@hdoro yes it seems to be fixed in the current version.
