### ISSUE TITLE
API client is versionless

### ISSUE THREAD

**Issue by eriklindebratt** [sanity-io/sanity-plugin-mux-input#31]
The API client used when e.g. fetching secrets does not specify Sanity API version, resulting in a deprecation warning, e.g.:

> Error: Used property "create" on versionless client - this is deprecated. Please specify API version using `withConfig` - see https://docs.sanity.io/help/studio-client-specify-api-version.

**Comment by rexxars** [comment]
Thanks for reporting - fixed in v1.0.0
