### ISSUE TITLE
No way to clear credentials? 

### ISSUE THREAD

**Issue by byebyers** [sanity-io/sanity-plugin-mux-input#317]
I am in a situation where I need to add different credentials for a client and have had no luck finding a way to do so. Is there no way to do this on the dashboard or a command line tool to clear the keys that have been set?

**Comment by essejmclean** [comment]
When you add a video there's a Configure API option in the more options menu.

Alternatively, you can delete the [document with _id "secrets.mux"](https://github.com/sanity-io/sanity-plugin-mux-input/blob/9e7ede327c57694249011dcf36ae3b61b8b48c97/src/actions/secrets.ts#L5) using the CLI: `sanity documents delete secrets.mux`

![CleanShot 2023-09-08 at 11 01 59@2x](https://github.com/sanity-io/sanity-plugin-mux-input/assets/21248254/b729bad1-6905-4fee-9809-3edfade202d1)

**Comment by byebyers** [comment]
@essejmclean thanks for sharing this. I deleted the keys in Mux so I did not see the configure API option but the command is a good back up.
