### ISSUE TITLE
Integration with @sanity/client

### ISSUE THREAD

**Issue by pastinepolenta** [sanity-io/sanity-plugin-mux-input#32]
@sanity/client allows to create documents with assets like images and files but I can't figure out an easy way to do so with Mux videos

See also: https://github.com/sanity-io/sanity-plugin-mux-input/issues/180

Perhaps we can get a client extension or some documentation on how to use this plugin for programmatic upload?

**Comment by hdoro** [comment]
@pastinepolenta I understand the value in this proposal, but this isn't something we can support in the native `@sanity/client`. That's a generic, multi-purpose library for all Sanity users, and tying it to Mux functionality would go beyond its scope and lead to bloat for the majority of use-cases.

We're discussing internally ways of synchronizing the video library in Sanity with assets in the configured Mux environment to pull uploaded videos not yet in Sanity. This way, you'd be able to submit programmatically to Mux as per [their upload documentation](https://docs.mux.com/guides/mux-uploader) and have the asset show up in Sanity.

I can't give you an ETA on this, but you can follow #53 and #342 for updates. Thank you for the patience!
