### ISSUE TITLE
Not able to "log out" from the plugin using the Access Tokens for client usage.

### ISSUE THREAD

**Issue by musaa-muhsen** [sanity-io/sanity-plugin-mux-input#326]
Hello all. I'm having trouble trying to "log out" using the Access tokens because I need to use Mux with the client account instead now. I've tried deleting the npm package, changing the schema stuff name, clearing caches, and general Chrome memory but still shows the same instance. Any suggestions would be great thanks.

**Comment by musaa-muhsen** [comment]
I deleted the document 'secrets.mux' which seemed successful after deletion, but it is still not resetting the credentials for Mux.

**Comment by hdoro** [comment]
@musaa-muhsen I'm not sure I follow what the issue is: you need to reset the credentials you have in your Mux plugin? If so, you're correct, we store them in the `secrets.mux` document.

What exactly do you mean by `resetting the credentials for Mux`?

**Comment by Rade58** [comment]
I made a mistake and deleted my access token? Is there a way to reenter credentials or to delete old ones which are not valid anymore?

**Comment by hdoro** [comment]
@Rade58 I've now added a note to the docs and a button to configure the plugin from the uploader /  video input. Hopefully this won't be an issue for others in the future, thank you for reporting 🙏
