### ISSUE TITLE
Support for auto-generated captions

### ISSUE THREAD

**Issue by slegay** [sanity-io/sanity-plugin-mux-input#327]
Mux recently released the ability to auto-generate subtitles. The feature can only be enabled during the initial MUX API request that creates the video asset. 

https://www.mux.com/blog/auto-generated-captions-for-on-demand-video-have-arrived-crowd-roars-with-applause

**Describe the solution you'd like**
We'd like the Mux Sanity plugin to offer an option to auto-generate captions.

**Describe alternatives you've considered**
We've tried adding this ourselves, but the plugin seems to make use of a server-side proxy to circumvent Mux's CORS rules that are preventing requests from browsers.

**Comment by thealice** [comment]
+1, this would be awesome.

**Comment by evankirkiles** [comment]
Yeah, I think this is generally in the hands of the Sanity team themselves to enable implementation. I also made an attempt, and the only [fields](https://docs.mux.com/api-reference#video/operation/create-direct-upload) that are proxied through to Mux in `new_asset_settings` when creating the direct upload link are the ones the plugin explicitly provides:

- `mp4_support` for specifying whether an MP4 should also be created

As that backend Sanity->Mux API proxy is not open-source, or at least I can't find its implementation anywhere, it would be a huge help to allow us to pass through additional arbitrary configuration options from the browser. At the very least, some documentation on what that endpoint `/addons/mux` is doing would be helpful in this plugin's README. I have a PR enabling more fine-tune configuration of a `mux.video`, e.g. by allowing specification of `encoding_tier`, `max_resolution_tier`, `master_access`, etc. on both a plugin-wide level and on a field-specific level, but until Sanity actually lets these options through the proxy any attempts on the side of an OS contributor will be in vain.

While the non-nested `new_asset_settings` options will be simple enough to provide support for (exposing them much like `mp4_support`, it might take a little bit more work to enable auto-generated captions, as these are set on the first element of the `new_asset_settings` `input` array.

@stipsan thoughts?

**Comment by hdoro** [comment]
This is now possible with plugin version `2.3.0` (see #350 ) ✅
