### ISSUE TITLE
No playbackid returned from sanity query

### ISSUE THREAD

**Issue by carstensbix** [sanity-io/sanity-plugin-mux-input#335]
I only get this information returned from my sanity query: (it's an mp4 i uploaded), i am on localhost

`video: {
    _type: 'mux.video',
    asset: {
      _ref: '938955fe-0d39-4011-9a70-a7dafb4866d2',
      _type: 'reference',
      _weak: true
    }
  },`
  
 How can i play an video without the playbackId? Can i use the _ref in any way?

**Comment by droplab** [comment]
you have to do a join on the _reference field to get the actual mux video data

```
video
{
   ...,
   "asset": asset->
}
```

**Comment by hdoro** [comment]
Thank you @droplab for the help!

@carstensbix as Mike pointed out above, you need to expand the video document reference in your Sanity query. You can [find an example in our Codesandbox demo](https://codesandbox.io/p/sandbox/github/sanity-io/sanity-plugin-mux-input/tree/main/example?file=%2Fsrc%2FVideo.js%3A15%2C1-16%2C1):

```ts
const query = /* groq */ `*[_type == "trailer"][0]{
  title,
  "playbackId": video.asset->playbackId
}`
```

Please refer to [References and Joins in Sanity's documentation](https://www.sanity.io/docs/how-queries-work#db43dfd18d7d) for more information.
