### ISSUE TITLE
Add Support for Styled Components v6

### ISSUE THREAD

**Issue by ahbyass** [sanity-io/sanity-plugin-mux-input#336]
**Describe the bug**
Now that sanity-ui supports styled components v6 and is the default in a new studio template, getting peer dependency issue.

**Comment by nicoskogen** [comment]
Any updates on this?

**Comment by stipsan** [comment]
Resolved in https://github.com/sanity-io/sanity-plugin-mux-input/releases/tag/v2.3.0
