### ISSUE TITLE
There is no way to choose between Baseline assets and Smart assets pricing 

### ISSUE THREAD

**Issue by WebShapedBiz** [sanity-io/sanity-plugin-mux-input#340]
Hi.

It seems that the plugin automatically uses a "Smart assets" pricing plan, ignoring the "Baseline assets" plan which is much cheaper while providing a good set of features.
Since "Baseline assets" is a new plan, according to Mux, could you make this selection available? Perhaps as a config option that can be added in sanity.config.js, the same as `mp4_support`?

Thank you for your time and effort.

**Comment by dylanjha** [comment]
Hi @WebShapedBiz -- we're working on this feature soon. Will let you know when that is added

**Comment by WebShapedBiz** [comment]
Thank you for this update @dylanjha

**Comment by WebShapedBiz** [comment]
Just a heads-up, MUX released a new, still in beta, "Cold Storage" pricing tier on January 17th, 2024. Here is the announcement:
https://www.mux.com/blog/introducing-our-coolest-pricing-lever-yet-automatic-cold-storage
