### ISSUE TITLE
Cannot access videos already uploaded to the MUX

### ISSUE THREAD

**Issue by WebShapedBiz** [sanity-io/sanity-plugin-mux-input#342]
Hi.

Since this plugin does not allow pricing tier selection or custom dimensions, I decided to upload some assets directly from the MUX dashboard, thinking that it would help me with my problems. However, to my repeated disappointment, this plugin only sees videos uploaded by it.
To recap, this plugin cannot properly upload videos to MUX nor can read videos already uploaded to MUX, so I'm wondering if this plugin is still maintained. Please let us know about it so that we stop wasting our time trying to make it work.

Cheers.

**Comment by mmcc** [comment]
Hi, Muxer here, sorry you're running into issues.

> this plugin cannot properly upload videos

To clarify, is this referring to the plugin not having the features you're looking for around tier selection/custom dimensions? Or are you running into an issue uploading videos altogether?

This plugin is actively maintained and I believe there are plans to add smart/baseline selection. We don't currently have plans to add the ability to import videos uploaded from outside of the plugin. Certainly not ideal, but you could always directly add Mux assets to your dataset as a short-term solution.

For the feature work, would you want these kinds of settings to be global (i.e., you want every asset you upload to be Baseline) or do you need the ability to configure each asset individually?

**Comment by WebShapedBiz** [comment]
Thank you @mmcc for your quick reply. I'm happy to see that this plugin is actively maintained because I believe that Sanity + MUX is the best combo for video monetization.
That being said, when I mention that "this plugin cannot properly upload videos" I meant that technically it can upload videos but not in a manner that one can use in a real-world use-case. Alongside missing the pricing selection, which I'm so happy that it's in the plans, there's also a topic about custom dimensions, something that is important as a way of custom video tagging for analytic purposes. Those custom dimensions are defined through the MUX dashboard settings panel and it would be nice if this plug-in could pick them up and present options in the upload video widget.

Regarding your question, off the top of my head, I would say that the pricing tier is something that MUX customer makes a decision on before using it, but I may be way off. Maybe MUX has something to offer on this subject since they can see how their users are using the platform.

Thank you again for your time and effort, you've been very helpful @mmcc

Cheers.

**Comment by dandc11** [comment]
@mmcc, when you say 

> We don't currently have plans to add the ability to import videos uploaded from outside of the plugin. 

do you mean that there are no plans to allow drag-and-drop or other upload into the "Videos" tab that the plugin creates in the Sanity Studio? If so, I'm really disappointed to hear. Our authors are confused by this, and, where videos need to be uploaded to the dataset outside of a typical workflow, they are currently having to add a video through the input to get it into the dataset and then manually remove it from a document. An upload feature similar to what's possible for images would be idea, allowing videos to be uploaded within and outside of documents. Just a suggestion : )

**Comment by hdoro** [comment]
Hey everyone 👋 

I'm happy to announce that importing existing videos from the configured Mux space is now possible with plugin version `2.3.0` (see #350 ) ✅

**Comment by WebShapedBiz** [comment]
Thank you @hdoro for your time and effort, great news.
