### ISSUE TITLE
Unable to import videos

### ISSUE THREAD

**Issue by WebShapedBiz** [sanity-io/sanity-plugin-mux-input#358]
**Describe the bug**

Hi,
as I understand, from the plugin version 2.3.0. it should be possible to import videos already present on MUX, not uploaded using this plugin, but on version 2.3.4. I'm getting a "No videos in this dataset" message for some reason. There are no errors in the console and I double-checked the Token ID and Secret.

**Which versions of Sanity are you using?**

@sanity/cli (global)          3.36.4 (up to date)
@sanity/cli                   3.36.4 (up to date)
@sanity/eslint-config-studio   4.0.0 (up to date)
@sanity/google-maps-input      4.0.0 (up to date)
@sanity/locale-hr-hr           1.1.5 (up to date)
@sanity/ui                     2.1.0 (up to date)
@sanity/vision                3.36.4 (up to date)
sanity                        3.36.4 (up to date)

**What operating system are you using?**

elementary OS 6.1 Jólnir (based on Ubuntu 20.04.6 LTS)

**Which versions of Node.js / npm are you running?**

npm: v10.2.4
node: v20.11.0

Thank you for maintaining this plugin

**Comment by WebShapedBiz** [comment]
Sorry for this, I just found out about the import button, I thought that the videos would be automatically browsable.

**Comment by Joobs** [comment]
@WebShapedBiz I am having the same issue, where is the option to import?

**Comment by WebShapedBiz** [comment]
Same here, I've seen it much later :-)

**Comment by btru775** [comment]
I can't get the videos tab to get past the swirl loading. No videos populate the dashboard and the plugin says my videos are already imported when I click import.
