### ISSUE TITLE
Error: Cannot read property 'from' of undefined

### ISSUE THREAD

**Issue by DanielHirunrusme** [sanity-io/sanity-plugin-mux-input#37]
Receiving error message 'Error: Cannot read property 'from' of undefined' in Sanity when trying to upload video and/or browsing selecting video. See loom here https://www.loom.com/share/475aed66dc724aa1bfe60cad3f1e77d6

This is with a fresh install of Sanity. Steps I took:

1. Sanity init
2. Chose the movie schema when creating sandbox Sanity
3. Did 'sanity install mux-input'
4. Added the schema in the quick start
5. Added new video reference in movie.js schema
6. Sanity start
7. Tried uploading MP4 video file
8. Upload works, but throws error message at end and won't display video
9. Refreshing, browse to select video I can see video uploaded but cannot select

The console error message is:
`react-dom.development.js:328 Uncaught TypeError: Cannot read property 'from' of undefined
    at Object.onSelect (Input.js:397)
    at SelectAsset.select (SelectAsset.js:98)
    at SelectAsset.select (react-hot-loader.development.js:717)
    at SelectAsset.js:40
    at HTMLUnknownElement.callCallback (react-dom.development.js:189)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:238)
    at invokeGuardedCallback (react-dom.development.js:293)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:307)
    at executeDispatch (react-dom.development.js:390)
    at executeDispatchesInOrder (react-dom.development.js:412)
(anonymous) @ Input.js:397
select @ SelectAsset.js:98
select @ react-hot-loader.development.js:717
(anonymous) @ SelectAsset.js:40
callCallback @ react-dom.development.js:189
invokeGuardedCallbackDev @ react-dom.development.js:238
invokeGuardedCallback @ react-dom.development.js:293
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:307
executeDispatch @ react-dom.development.js:390
executeDispatchesInOrder @ react-dom.development.js:412
executeDispatchesAndRelease @ react-dom.development.js:3279
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:3288
forEachAccumulated @ react-dom.development.js:3260
runEventsInBatch @ react-dom.development.js:3305
runExtractedPluginEventsInBatch @ react-dom.development.js:3515
handleTopLevel @ react-dom.development.js:3559
batchedEventUpdates$1 @ react-dom.development.js:21872
batchedEventUpdates @ react-dom.development.js:796
dispatchEventForLegacyPluginEventSystem @ react-dom.development.js:3569
attemptToDispatchEvent @ react-dom.development.js:4268
dispatchEvent @ react-dom.development.js:4190
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11040
discreteUpdates$1 @ react-dom.development.js:21888
discreteUpdates @ react-dom.development.js:807
dispatchDiscreteEvent @ react-dom.development.js:4169
createStore.js:30 Error: Invalid call to useReporter(field-video.video): A component reporting on "field-video.video" is already mounted in the subtree. Make sure that all reporters within the same <Tracker> subtree have unique ids.
    at add (createStore.js:30)
    at createUseReporter.js:42
    at commitHookEffectListMount (react-dom.development.js:19732)
    at commitLifeCycles (react-dom.development.js:19788)
    at commitLayoutEffects (react-dom.development.js:22804)
    at HTMLUnknownElement.callCallback (react-dom.development.js:189)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:238)
    at invokeGuardedCallback (react-dom.development.js:293)
    at commitRootImpl (react-dom.development.js:22542)
    at unstable_runWithPriority (scheduler.development.js:653)`

Help please! :)

**Comment by KimPaow** [comment]
@DanielHirunrusme Thanks for reporting this, can you share your list of sanity dependencies? @sanity/base etc.

**Comment by DanielHirunrusme** [comment]
Here is my package.json

`{
  "name": "sanitytest",
  "private": true,
  "version": "1.0.0",
  "description": "",
  "main": "package.json",
  "author": "Daniel Hirunrusme <daniel@halfhalf.us>",
  "license": "UNLICENSED",
  "scripts": {
    "start": "sanity start",
    "build": "sanity build"
  },
  "keywords": [
    "sanity"
  ],
  "dependencies": {
    "@sanity/base": "^2.12.0",
    "@sanity/components": "^2.2.6",
    "@sanity/core": "^2.12.0",
    "@sanity/default-layout": "^2.12.0",
    "@sanity/default-login": "^2.11.1",
    "@sanity/desk-tool": "^2.12.1",
    "@sanity/google-maps-input": "^2.12.0",
    "@sanity/vision": "^2.11.2",
    "prop-types": "^15.7",
    "react": "^17.0",
    "react-dom": "^17.0",
    "react-icons": "^3.11.0",
    "sanity-plugin-mux-input": "^1.0.0"
  },
  "devDependencies": {}
}
`

My sanity.json

`{
  "root": true,
  "project": {
    "name": "sanityTest"
  },
  "api": {
    "projectId": "4bw8gcec",
    "dataset": "production"
  },
  "plugins": [
    "@sanity/base",
    "@sanity/components",
    "@sanity/default-layout",
    "@sanity/default-login",
    "@sanity/desk-tool",
    "@sanity/google-maps-input",
    "mux-input"
  ],
  "env": {
    "development": {
      "plugins": [
        "@sanity/vision"
      ]
    }
  },
  "parts": [
    {
      "name": "part:@sanity/base/schema",
      "path": "./schemas/schema"
    }
  ]
}
`

movie.js schema
`import { MdLocalMovies as icon } from 'react-icons/md'

export default {
  name: 'movie',
  title: 'Movie',
  type: 'document',
  icon,
  fields: [
    {
      name: 'title',
      title: 'Title',
      type: 'string',
    },
    {
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: {
        source: 'title',
        maxLength: 100,
      },
    },
    {
      name: 'overview',
      title: 'Overview',
      type: 'blockContent',
    },
    {
      name: 'releaseDate',
      title: 'Release date',
      type: 'datetime',
    },
    {
      name: 'video',
      type: 'video'
    },
    {
      name: 'externalId',
      title: 'External ID',
      type: 'number',
    },
    {
      name: 'popularity',
      title: 'Popularity',
      type: 'number',
    },
    {
      name: 'poster',
      title: 'Poster Image',
      type: 'image',
      options: {
        hotspot: true,
      },
    },
    {
      name: 'castMembers',
      title: 'Cast Members',
      type: 'array',
      of: [{ type: 'castMember' }],
    },
    {
      name: 'crewMembers',
      title: 'Crew Members',
      type: 'array',
      of: [{ type: 'crewMember' }],
    },
  ],
  preview: {
    select: {
      title: 'title',
      date: 'releaseDate',
      media: 'poster',
      castName0: 'castMembers.0.person.name',
      castName1: 'castMembers.1.person.name',
    },
    prepare(selection) {
      const year = selection.date && selection.date.split('-')[0]
      const cast = [selection.castName0, selection.castName1].filter(Boolean).join(', ')

      return {
        title: `${selection.title} ${year ? `(${year})` : ''}`,
        date: selection.date,
        subtitle: cast,
        media: selection.media,
      }
    },
  },
}
`

video.js schema
`export default {
    title: "Video blog post",
    name: "video",
    type: "document",
    fields: [
        { title: "Title", name: "title", type: "string" },
        {
            title: "Video file",
            name: "video",
            type: "mux.video"
        }
    ]
}`

**Comment by bjoerge** [comment]
Thanks for reporting! A fix for this was shipped in [v2.12.2](https://github.com/sanity-io/sanity/releases/tag/v2.12.2) so it should work again now.

**Comment by DanielHirunrusme** [comment]
@bjoerge @KimPaow Thank you! It's working for me now!
