### ISSUE TITLE
Mux.video type name breaks sanity-codegen type generation

### ISSUE THREAD

**Issue by RobEasthope** [sanity-io/sanity-plugin-mux-input#41]
I'm using the sanity-codegen plugin to generate typescript types across my project but it's throwing an error due the full stop in the mux.video schema type name.
```
Error: Name "mux.video" is not valid. Ensure camel case, alphanumeric, and underscore characters only
    at validatePropertyName (/Users/rob/Code/ida-io/sanity/node_modules/sanity-codegen/generate-types.js:14:11)
```

I appreciate it's a third-party plugin and not the responsibilty of the authors of this repo but does anyone have an suggestions? Is it possble to alias the name in some form? Short of forking the whole plugin I can't think of a solution

Anybody got any ideas for a workaround?

P.S. I've [raised an issue](https://github.com/ricokahler/sanity-codegen/issues/145) in the sanity-codegen repo as well if it'll help

**Comment by dylanjha** [comment]
Thanks for surfacing @RobEasthope -- I hadn't seen sanity-codegen before. Seems like that lib is enforcing this rule around schema type names.

I'm looking at that library to see if there's a way to ignore a particular schema name, or ignore 3rd party plugins, but there doesn't seem to be.

I'll follow along on the sanity-codegen issue that you opened

**Comment by ricokahler** [comment]
This was definitely an issue upstream. [All fixed now](https://github.com/ricokahler/sanity-codegen/issues/145) 😄 . Thanks for raising this!

**Comment by dylanjha** [comment]
@ricokahler thanks so much for the quick turn around!
