### ISSUE TITLE
Signed URL support?

### ISSUE THREAD

**Issue by bradley** [sanity-io/sanity-plugin-mux-input#46]
As far as I can tell, youre able to set up assets on the Sanity end to upload and use signed URLs (some proof here being that they display fine in Sanity and you can see `?token=...` in their URLs in the Network tab). However, actually consuming these resources over the Sanity API to your frontend does not appear to work, as there doesn't seem to be a way to request down the asset's `playbackId` etc along with the required tokens you'd need to get these resources on the frontend (e.g.; without the `token` in their formatted URLs, you end up getting `403` responses from Mux within your app).

Is there any way to get signed URLs into your frontend over Sanity's API?

**Comment by dylanjha** [comment]
Hi @bradley you will need to create a signing key pair and generate signed URLs on your server. More [details here](https://docs.mux.com/guides/video/integrate-with-sanity#advanced-signed-urls)

Generating signed URLs client-side is not possible, as that would require exposing your signing keys in the client.

**Comment by bradley** [comment]
@dylanjha Oh ok, that makes sense. Was hoping that was something Sanity would do before returning data with each API request, but makes sense. Best.

**Comment by dylanjha** [comment]
Yeah, unfortunately we don't have a way to run server-side code with a Sanity plugin
