### ISSUE TITLE
Video preview in sanity studio displays the wrong video

### ISSUE THREAD

**Issue by bitzky** [sanity-io/sanity-plugin-mux-input#48]
I found a strange bug in sanity studio. Every time I click on a new video, it shows me the video that I clicked right before. The first video that I click is empty. 

After deleting everything, upgrading to sanity 2.21.0 and MuxInput 1.1.0 and uploading some videos again, the bug still remained.

https://user-images.githubusercontent.com/8150506/137128688-74ddb190-de25-4679-b905-670a36e0e68d.mov

**Comment by hdoro** [comment]
Assuming stale - the plugin's approach to previews changed significantly and this is probably not an issue anymore
