### ISSUE TITLE
Module should potentially be using named exports instead of exporting an object

### ISSUE THREAD

**Issue by gpoole** [sanity-io/sanity-plugin-mux-input#49]
The module exports from this plugin seem to be [an object exported as `default` with the components as properties](https://github.com/sanity-io/sanity-plugin-mux-input/blob/main/src/index.js#L4), instead of named exports. Because of that the following does not work as I expected:

```jsx
import MuxInputPlugin, { Preview }  from 'sanity-plugin-mux-input'

console.log(Preview)
//null

console.log(MuxInputPlugin.Preview)
// (the component)
```

I think from a user perspective this is confusing and might be worth changing to named exports?

**Comment by hdoro** [comment]
Thank you for reporting and sorry for the wait on getting back to you, Greg!

This has been solved with the Sanity V3 versions of this plugin (`^2.0.0`) ✅
