### ISSUE TITLE
Audio files render a large black placeholder

### ISSUE THREAD

**Issue by geball** [sanity-io/sanity-plugin-mux-input#51]
When an audio file is uploaded, a large black placeholder is rendered in the studio.

<img width="582" alt="A black placeholder is rendered when an audio file is uploaded." src="https://user-images.githubusercontent.com/45116528/139480526-b3791156-6332-4944-a2ac-d3876c99751a.png">

The mux-input plugin is using the media-chrome package, which is applying this CSS rule:

```css
:host(:not([audio])) {
    height: 480px;
    width: 720px;
}
```

However, `media-controller` in the [Video component](https://github.com/sanity-io/sanity-plugin-mux-input/blob/fbff5da2aba6e975b466f69328853a4a6d25d0a9/src/components/Video.js) does not appear to apply the audio attribute, which would remove the large placeholder.

https://user-images.githubusercontent.com/45116528/139481057-7e95453d-b93e-4087-8615-df3faeeb6537.mov

**Comment by hdoro** [comment]
Hey Geoff, long time no see! 👋 

Fixed as of upcoming `2.4.0` - see this comment: https://github.com/sanity-io/sanity-plugin-mux-input/issues/128#issuecomment-2121100263
