### ISSUE TITLE
Link up Existing Video in Mux

### ISSUE THREAD

**Issue by davidalexander** [sanity-io/sanity-plugin-mux-input#53]
Hi. Thanks so much for the plugin.

Can I ask if there's a way to associate/select a video asset that already exists in Mux e.g. by its asset ID?

Effectively, we are implementing Sanity as the CMS and need to move the existing video assets into it but don't want to re-upload them all.

Thanks!

**Comment by bitterbit** [comment]
I gave this a try today but got stuck
* I added "Import" an import button to `src/components/Input.js` 
* and creating `src/components/ImportAsset.js` to be the popup that lists the assets that are available on the mux servers

 
I got stuck when I saw that mux api access (`src/actions/assets.js`) does not query mux directly 
rather use a local endpoint (`/addons/mux/assets`) which has no documentation. 

If someone knows which endpoint under sanity's `/addons/mux` returns a list of all assets that would be great 👀

**Comment by Ojay** [comment]
I've a similar need to this.... we're migrating an old WordPress setup over to Sanity and so need to link up our Mux Input with the data from WP. 

Would I be right in thinking that we'd need to batch import all of our Mux data into Sanity as a `mux.videoAsset` and then go about linking up the Mux Input to the relevant `mux.videoAsset`?

Essentially, we're looking for guidance on migrating existing setups to Sanity / Mux Input setups.

Thanks for an amazing plugin and just generally being awesome... I absolutely love Sanity!

Cheers

**Comment by danielskogstad** [comment]
We have over 2000 existing videos uploaded to mux that we use in our app. We hoped the Sanity mux plugin would allow us to browse and pick videos from the library, so we could showcase some of them on the website to promote our app content, but this plugin seems to only allow uploading new ones.

**Comment by lukasentebbe** [comment]
Any Progress here? I think without being able to see/pull existing Mux Videos the connection is kind of useless.

**Comment by williswcy** [comment]
Is there any plan for implementing this? If not, I need to consider other alternatives

**Comment by khushkaranbajwa** [comment]
I don't suppose there's been an update here?

**Comment by hdoro** [comment]
Hey everyone 👋 

I'm happy to announce that importing existing videos from the configured Mux space is now possible with plugin version `2.3.0` (see #350 ) ✅
