### ISSUE TITLE
Asset is sometimes empty in production build

### ISSUE THREAD

**Issue by zanedev** [sanity-io/sanity-plugin-mux-input#57]
For some reason the mux asset in Gatsby is sometimes an empty object in production build with no playbackid. We fixed it by temporarily hard coding the playbackID in the front end.

Is this an issue with the mux sanity input or sanity's api or gatsby somehow?

**Comment by jimmi-joensson** [comment]
Believe I just experienced the same. Asset kept returning as null in my Sanity data

**Comment by mitch-john** [comment]
Experiencing the same with Sanity and Gatsby.

**Comment by palmerama** [comment]
I'm having the same issue. Seems like a quick fix to get done properly. Is it likely to happen soon?

**Comment by stipsan** [comment]
Hey y'all, can you test [`v1.1.4`](https://github.com/sanity-io/sanity-plugin-mux-input/releases/tag/v1.1.4) and see if it fixes it? 😄

**Comment by intelligence** [comment]
I'm still seeing this issue in Gatsby. It will work for some time, then for some reason come back as null. If you do `gatsby clean` and then run `gatsby dev` it works again. Ping @stipsan

**Comment by palmerama** [comment]
Me too! It does set _type to _reference, but that doesn't fix the issue. I gave up in the end and had to write a hugely convoluted custom publish script to pull all the data I need into fields, so it can't just disappear. Not ideal.

**Comment by intelligence** [comment]
Related to this https://github.com/sanity-io/gatsby-source-sanity/issues/154, perhaps?

**Comment by intelligence** [comment]
@palmerama Would you be able to share your solution? I'm moving into production with a site soonish and this issue is a blocker at the moment.

**Comment by zanedev** [comment]
@intelligence last resort you could write a build script to use the [sanity json api](https://www.sanity.io/docs/js-client) instead of the graphql endpoint to pull the mux data during build time then inject it into your gatsby site using an env variable or a gatsby source plugin to read it from a file

**Comment by intelligence** [comment]
I think I may have found the underlying issue for why it turns up empty.

Adding:
`sanityDocTypes.push('SanityMuxVideo', 'SanityMuxVideoAsset')`

After:
https://github.com/sanity-io/gatsby-source-sanity/blob/main/src/gatsby-node.ts#L301
...seems to do the trick. I have no idea how to achieve this in a cleaner way though. For some reason those doc types are not included when looking through the cache.

**Comment by hdoro** [comment]
This is now fixed with the upcoming `2.4.0`

See: https://github.com/sanity-io/sanity-plugin-mux-input/issues/43#issuecomment-2121071213
