### ISSUE TITLE
large uploads fail

### ISSUE THREAD

**Issue by good-idea** [sanity-io/sanity-plugin-mux-input#8]
Perhaps the same as #5, but, the POST data is showing up fine in the network tab.

I'm uploading a 500mb video file, which is taking about 6 minutes on my connection. After the upload reaches 100%, I see "Unexpected error occurred":

![image](https://user-images.githubusercontent.com/11514928/65790030-8005c200-e113-11e9-8458-fa833b2f97ae.png)

In the network tab, the request has failed with a 400 status. Here's what is in the Chrome network tab:

#### General
```
Request URL: https://ddpo9nmo.api.sanity.io/v1/addons/mux/assets/production?muxBody=%7B%22input%22%3A%22%22%2C%22playback_policy%22%3A%5B%22public%22%5D%7D&filename=kusama-original.mp4
Request Method: POST
Status Code: 400 
Remote Address: 35.241.31.122:443
Referrer Policy: no-referrer-when-downgrade
```

#### Response Headers
```
access-control-allow-credentials: true
access-control-allow-origin: https://onehundredyearplan.sanity.studio
access-control-expose-headers: Content-Type, Content-Length, ETag, X-Sanity-Deprecated, X-Sanity-Warning
access-control-max-age: 600
alt-svc: clear
content-length: 81
content-type: application/json; charset=utf-8
date: Fri, 27 Sep 2019 17:37:41 GMT
etag: W/"51-BqXby0DlGrHHO5RU6zvKO8edQhI"
status: 400
vary: Origin
via: 1.1 google
```

#### Request Headers
```
Provisional headers are shown
Accept: application/json
Content-Type: video/mp4
DNT: 1
MUX-Proxy-UUID: [redacted]
Origin: https://onehundredyearplan.sanity.studio
Referer: https://onehundredyearplan.sanity.studio/desk/websites;c203233e-ba1f-47f0-bc31-24d727370fe0
Sec-Fetch-Mode: cors
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
```

### Query String Parameters
```
muxBody: {"input":"","playback_policy":["public"]}
filename: kusama-original.mp4
```

The video *has* successfully uploaded to MUX, it shows up in the dashboard there. But, it's never registered as an asset in Sanity, so it can't be added to the document later.

**Edit**: I just tried uploading a smaller video (30mb) with the network throttled. It took 5.9 minutes and failed in the same way.

**Comment by david-j-davis** [comment]
I'm having the same issue happening repeatedly as well as of today. I'm uploading a video of around 350mb. My videos also successfully upload to Mux dashboard like @good-idea

**Comment by evenwestvang** [comment]
Thank you for this – we'll investigate.

**Comment by good-idea** [comment]
@david-j-davis as a little workaround -- if you're using the Structure plugin, you can manually add your Mux assets with a setup like this:

```js
import S from '@sanity/desk-tool/structure-builder'

export default () =>
  S.list()
    .title('My Site')
    .items([
      S.listItem()
        .title('Pages')
        .child(S.documentTypeList('page')),
      S.listItem()
        .title('Videos')
        .child(S.documentTypeList('mux.videoAsset')),
    ])
```

It's a bit of a "hack", and the display title for all of the documents will be "ready", but you can add a new one, manually enter `ready` as the status, the asset ID and playback ID, which you can copy from your Mux dashbord:

![image](https://user-images.githubusercontent.com/11514928/66151984-4a5a5080-e5cd-11e9-80e2-fbfd01667c58.png)

Then, back in your video field, you can select Browse instead of upload, and you should the the thumbnail

**Comment by david-j-davis** [comment]
Thanks @good-idea for the back-up plan. My client can wait maybe a week before I'll have to do this if there isn't a fix in place by the Sanity team.

**Comment by good-idea** [comment]
@david-j-davis no problem. If it's helpful at all, I wrote a simple CLI for uploading directly to Mux. My client had a big batch of videos to upload, and this made it a lot easier.

https://github.com/good-idea/100-year-plan/tree/master/mux-upload

Packaged as a standalone script (just a zip from my dropbox):

https://www.dropbox.com/s/wdge4i4xalewocg/mux-upload.zip?dl=0

(run that with `./mux-upload my-video.mp4 another-video.mp4`)

The Readme there says to create a `.env` file - you can ignore this if you'd like, I made a recent update that prompts you for your API credentials and saves them to `~/.mux-credentials`.

You'll still need to manually enter the asset & playback IDs - but, it wouldn't be too difficult to write another "syncing" script that fetches all of your video assets from MUX and creates the proper documents in Sanity

**Comment by skogsmaskin** [comment]
Hi! We have released `v.0.2.1` today, which I think will solve these problems. It's using the new resumable direct upload to MUX and should work better for larger files. Let me know if you still experiencing problems. I'm closing this now.

**Comment by sachinkaria** [comment]
Still experiencing this issues with larger videos

**Comment by skogsmaskin** [comment]
Are you sure you're running the latest version @sachinkaria? What is the error?

**Comment by sachinkaria** [comment]
Hi @skogsmaskin we narrowed down the issue to the pollUpload - maxTries variable (we set it to 200 to test), for larger videos this worked :)

![image](https://user-images.githubusercontent.com/8612895/69328713-a0e82080-0c47-11ea-82a7-7e435c52f376.png)

**Comment by cordial** [comment]
> Hi, trying to upload a 15gb file (5 hours long video) and experiencing a timeout issue as well. It gets about 20% of the way through and then stops. As an alternative, I tried this https://github.com/muxinc/stream.new and was able to successfully upload the file but it does not appear in my Mux library within Sanity. I then tried the above method @good-idea suggested but having trouble with the video because it's perhaps "signed". Any ideas?
> 
> Using "sanity-plugin-mux-input": "^2.2.3" and "sanity": "^3.18.0".
> 
> Entire package json below
> 
> ```json
> {
>   "private": true,
>   "scripts": {
>     "build": "next build",
>     "postbuild": "next-sitemap",
>     "dev": "next",
>     "dev-local": "npx next dev -H 192.168.1.196 -p 3000",
>     "format": "npx prettier --write . --ignore-path .gitignore --cache",
>     "lint": "next lint -- --ignore-path .gitignore",
>     "lint:fix": "npm run format && npm run lint -- --fix",
>     "start": "next start",
>     "studio:deploy": "npx vercel env pull && npm --prefix studio run deploy",
>     "studio:dev": "npm --prefix studio run start",
>     "type-check": "tsc --noEmit"
>   },
>   "prettier": {
>     "semi": false,
>     "singleQuote": true
>   },
>   "dependencies": {
>     "@headlessui/react": "^1.7.13",
>     "@mux/mux-node": "^7.3.0",
>     "@mux/mux-player-react": "^1.11.4",
>     "@mux/videojs-kit": "^0.11.4",
>     "@portabletext/react": "^2.0.2",
>     "@react-pdf/renderer": "^3.1.9",
>     "@sanity/block-content-to-react": "^3.0.0",
>     "@sanity/color-input": "^3.0.2",
>     "@sanity/image-url": "^1.0.1",
>     "@sanity/scheduled-publishing": "^1.2.1",
>     "@sanity/vision": "^3.8.3",
>     "@sanity/webhook": "^2.0.0",
>     "algoliasearch": "^4.17.0",
>     "auto-text-size": "^0.2.2",
>     "classnames": "^2.3.1",
>     "date-fns": "^2.29.1",
>     "framer-motion": "^10.12.4",
>     "hls.js": "^1.4.0",
>     "i": "^0.3.7",
>     "intl-segmenter-polyfill": "^0.4.4",
>     "moment": "^2.29.4",
>     "moment-timezone": "^0.5.43",
>     "next": "^13.3.0",
>     "next-sanity": "^4.1.6",
>     "next-sitemap": "^4.1.3",
>     "next-use-contextual-routing": "^3.0.1",
>     "nextjs-google-analytics": "^2.3.3",
>     "npm": "^9.6.5",
>     "plyr-react": "^5.2.0",
>     "react": "^18.2.0",
>     "react-accessible-accordion": "^5.0.0",
>     "react-countdown": "^2.3.5",
>     "react-dom": "^18.2.0",
>     "react-hook-form": "^7.38.0",
>     "react-icons": "^4.8.0",
>     "react-idle-timer": "^5.6.2",
>     "react-instantsearch-dom": "^6.39.1",
>     "react-intersection-observer": "^9.4.0",
>     "react-modal": "^3.16.1",
>     "react-moment-countdown": "^0.4.2",
>     "react-player": "^2.12.0",
>     "react-tabs": "^5.2.0",
>     "reduce-css-calc": "^2.1.8",
>     "sanity": "^3.18.0",
>     "sanity-algolia": "^1.1.0",
>     "sanity-plugin-mux-input": "^2.2.3",
>     "satori": "^0.4.7",
>     "styled-components": "^5.3.9",
>     "suspend-react": "^0.0.9",
>     "swiper": "^9.2.0",
>     "swr": "^2.1.3",
>     "typewriter-effect": "^2.19.0",
>     "use-fit-text": "^2.4.0",
>     "use-mailchimp-form": "^3.1.0",
>     "video.js": "^8.3.0"
>   },
>   "devDependencies": {
>     "@types/node": "18.15.11",
>     "autoprefixer": "^10.4.8",
>     "eslint": "^8.38.0",
>     "eslint-config-next": "^13.3.0",
>     "eslint-plugin-simple-import-sort": "^10.0.0",
>     "postcss": "^8.4.14",
>     "prettier": "^2.8.7",
>     "prettier-plugin-packagejson": "^2.4.3",
>     "prettier-plugin-tailwindcss": "^0.2.7",
>     "react-moment-proptypes": "^1.8.1",
>     "tailwindcss": "^3.3.1",
>     "typescript": "5.0.4"
>   },
>   "engines": {
>     "node": ">=16"
>   }
> }
> ```

hey, im having similar issues, did u manage to do it successfully in the end?
